### ISSUE TITLE
Convert to compile dependency

### ISSUE THREAD

**Issue by joebowbeer** [devdev-dev/PureDataSampleProject#1]
Consider modifying this project to use a gradle compile dependency on the [pd-for-android](https://github.com/libpd/pd-for-android) library artifact that is now available from the jCenter repository.

http://stackoverflow.com/a/27770809/901597

**Comment by devdev-dev** [comment]
I updated the project to match the new condition of the pd-for-android project. I like the jCenter repository integration and the easy to use gradle dependency.

Thanks for your great work!
